In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
playoffs2019traditional = pd.read_excel("nbadata2950.xlsx", sheet_name = "outplayofftrad")
playoffs2019advanced = pd.read_excel("nbadata2950.xlsx", sheet_name = "outplayoffadv")

In [3]:
playoffs2019traditional.head()
playoffs2019traditional.shape

(16, 28)

In [4]:
playoffs2019advanced = playoffs2019advanced.drop([0])
playoffs2019advanced.shape

(16, 20)

In [5]:
playoffs2019advanced.head()

,Unnamed: 0,TEAM,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,AST/TO,AST,OREB%,DREB%,REB%,TOV%,EFG%,TS%,PACE,PIE
1,1.0,Los Angeles Lakers,18.0,14.0,4.0,864.0,116.1,108.8,7.2,62.9,1.68,18.9,30.3,76.0,53.4,15.8,56.4,59.8,98.28,55.1
2,2.0,Miami Heat,18.0,13.0,5.0,874.0,113.5,110.5,3.0,66.1,1.94,18.8,24.4,73.9,49.9,13.2,54.1,59.1,97.15,52.8
3,3.0,Boston Celtics,17.0,10.0,7.0,831.0,111.6,106.3,5.3,58.7,1.62,17,26.1,74.7,51.4,14.2,52.7,57.2,96.32,53.1
4,4.0,Denver Nuggets,19.0,9.0,10.0,917.0,112.6,115.0,-2.4,58.0,1.62,17.3,27.9,72.2,50.2,14.6,54.5,58.4,94.87,49.1
5,5.0,LA Clippers,13.0,7.0,6.0,629.0,114.4,110.1,4.2,51.7,1.63,16,25.3,76.2,50.5,13.0,54.4,58.5,98.90,51.3

In [6]:
playoffs2019 = pd.merge(playoffs2019traditional, playoffs2019advanced, how = 'inner', on = 'TEAM')

In [7]:
playoffs2019

,Unnamed: 0_x,TEAM,GP_x,W_x,L_x,WIN%,MIN_x,PTS,FGM,FGA,...,AST/TO,AST_y,OREB%,DREB%,REB%,TOV%,EFG%,TS%,PACE,PIE
0,1,Los Angeles Lakers,18,14,4,0.778,48.0,114.1,41.4,84.1,...,1.68,18.9,30.3,76.0,53.4,15.8,56.4,59.8,98.28,55.1
1,2,Miami Heat,18,13,5,0.722,48.6,111.7,38.2,82.6,...,1.94,18.8,24.4,73.9,49.9,13.2,54.1,59.1,97.15,52.8
2,3,Toronto Raptors,11,7,4,0.636,48.9,109.4,39.1,88.5,...,1.90,18.2,22.6,75.9,49.2,13.0,52.5,55.9,98.63,51.5
3,4,Boston Celtics,17,10,7,0.588,48.9,109.4,38.6,84.9,...,1.62,17,26.1,74.7,51.4,14.2,52.7,57.2,96.32,53.1
4,5,LA Clippers,13,7,6,0.538,48.4,114.0,40.9,86.4,...,1.63,16,25.3,76.2,50.5,13.0,54.4,58.5,98.90,51.3
5,6,Milwaukee Bucks,10,5,5,0.500,48.5,111.1,40.1,87.1,...,1.63,17.7,23.0,79.1,50.6,14.6,53.7,56.8,101.05,50.2
6,7,Denver Nuggets,19,9,10,0.474,48.3,107.4,38.8,82.5,...,1.62,17.3,27.9,72.2,50.2,14.6,54.5,58.4,94.87,49.1
7,8,Oklahoma City Thunder,7,3,4,0.429,48.7,104.0,36.7,85.4,...,1.05,13.5,25.3,81.6,53.8,16.6,50.0,54.2,100.65,48.2
8,8,Utah Jazz,7,3,4,0.429,48.7,113.4,39.9,81.9,...,1.79,16.8,26.0,71.2,49.1,12.7,58.3,61.6,92.83,51.7
9,10,Houston Rockets,12,5,7,0.417,48.4,107.7,37.4,85.8,...,1.59,16.3,18.9,73.3,45.2,13.4,53.5,56.9,99.18,48.0
10,11,Dallas Mavericks,6,2,4,0.333,48.8,117.0,42.2,89.2,...,1.70,15.8,21.6,77.9,49.2,12.1,54.9,58.0,102.55,46.3
11,12,Orlando Magic,5,1,4,0.200,48.0,107.0,37.2,88.6,...,1.63,17.3,17.2,78.0,46.4,13.9,50.5,54.7,104.60,44.6
12,12,Portland Trail Blazers,5,1,4,0.200,48.0,106.6,37.6,88.2,...,1.11,13.2,27.7,70.4,48.4,15.6,49.2,53.7,102.40,41.5
13,14,Brooklyn Nets,4,0,4,0.000,48.0,105.8,36.3,91.3,...,1.78,17.9,26.4,76.4,48.8,14.0,48.2,51.8,103.00,38.8
14,14,Indiana Pacers,4,0,4,0.000,48.0,100.8,36.5,80.3,...,1.48,17.6,18.5,71.0,44.7,15.7,53.0,56.5,97.88,43.4
15,14,Philadelphia 76ers,4,0,4,0.000,48.0,100.5,33.3,84.0,...,1.46,13.5,31.6,72.5,51.3,12.5,44.3,51.2,95.75,44.6

In [8]:
playoffs2019.columns

Index(['Unnamed: 0_x', 'TEAM', 'GP_x', 'W_x', 'L_x', 'WIN%', 'MIN_x', 'PTS',
       'FGM', 'FGA', 'FG%', '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB',
       'DREB', 'REB', 'AST_x', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-',
       'Unnamed: 0_y', 'GP_y', 'W_y', 'L_y', 'MIN_y', 'OFFRTG', 'DEFRTG',
       'NETRTG', 'AST%', 'AST/TO', 'AST_y', 'OREB%', 'DREB%', 'REB%', 'TOV%',
       'EFG%', 'TS%', 'PACE', 'PIE'],
      dtype='object')

In [9]:
playoffs2019 = playoffs2019.drop(columns = ['GP_y', 'W_y', 'L_y', 'Unnamed: 0_y', 'Unnamed: 0_x'])

In [10]:
playoffs2019 = playoffs2019.rename(columns = {"GP_x": "GP", "W_x": "W", "L_x": "L","MIN_x": "MPG", "AST_x": "APG", "MIN_y": "Tot Mins", "AST_y": "AST_Ratio"})

In [11]:
playoffs2019.head()

,TEAM,GP,W,L,WIN%,MPG,PTS,FGM,FGA,FG%,...,AST/TO,AST_Ratio,OREB%,DREB%,REB%,TOV%,EFG%,TS%,PACE,PIE
0,Los Angeles Lakers,18,14,4,0.778,48.0,114.1,41.4,84.1,49.3,...,1.68,18.9,30.3,76.0,53.4,15.8,56.4,59.8,98.28,55.1
1,Miami Heat,18,13,5,0.722,48.6,111.7,38.2,82.6,46.2,...,1.94,18.8,24.4,73.9,49.9,13.2,54.1,59.1,97.15,52.8
2,Toronto Raptors,11,7,4,0.636,48.9,109.4,39.1,88.5,44.2,...,1.90,18.2,22.6,75.9,49.2,13.0,52.5,55.9,98.63,51.5
3,Boston Celtics,17,10,7,0.588,48.9,109.4,38.6,84.9,45.4,...,1.62,17,26.1,74.7,51.4,14.2,52.7,57.2,96.32,53.1
4,LA Clippers,13,7,6,0.538,48.4,114.0,40.9,86.4,47.4,...,1.63,16,25.3,76.2,50.5,13.0,54.4,58.5,98.90,51.3

In [12]:
playoffs2019.columns

Index(['TEAM', 'GP', 'W', 'L', 'WIN%', 'MPG', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'APG',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-', 'Tot Mins', 'OFFRTG',
       'DEFRTG', 'NETRTG', 'AST%', 'AST/TO', 'AST_Ratio', 'OREB%', 'DREB%',
       'REB%', 'TOV%', 'EFG%', 'TS%', 'PACE', 'PIE'],
      dtype='object')